services:
  dev-env:
    image: arm-m-ridiculus-startup
    build:
      context: .
      args:
        BASE_IMAGE: 'psugrg/gcc-arm-none-eabi-dev:v0.1'
    tty: true
    working_dir: /home/${USER}/project
    volumes:
      - ./:/home/${USER}/project
      - /dev/bus/usb:/dev/bus/usb
    group_add:
      - dialout
      - plugdev
    privileged: true
